repos:
-   repo: local
    hooks:
    -   id: quality-check-all
        name: Run all quality checks
        entry: make quality-check-all
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-commit]
        exclude: ^(migrations/|management/|tests/|static/|media/)