version: 0.2

phases:
  build:
    runtime-versions:
      python: 3.12.0
    commands:
      - |
        pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        poetry install
        poetry install --no-interaction --no-ansi
        poetry run python manage.py migrate --noinput
        poetry run python manage.py collectstatic --noinput
        zip -r ../app.zip . -x "*.git*" "media/*" "media-/*" "*.pyc" "*__pycache__*"
        echo "Build and packaging complete."

artifacts:
  files:
    - ../app.zip