version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.0
    commands:
      - pip install --upgrade pip
      # Install Poetry explicitly and ensure it's in PATH
      - curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
      - echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc
      - source ~/.bashrc  # Reload shell to apply PATH
      - which poetry || echo "Poetry not found!"  # Debug: Check if Poetry is installed
      - poetry --version  # Debug: Verify Poetry is callable
      - poetry install --no-interaction --no-ansi

  pre_build:
    commands:
      - source ~/.bashrc  # Ensure PATH is set
      - poetry run python manage.py migrate --noinput
      - poetry run python manage.py collectstatic --noinput

  build:
    commands:
      - zip -r ../app.zip . -x "*.git*" "media/*" "media-/*" "*.pyc" "*__pycache__*"

  post_build:
    commands:
      - echo "Build and packaging complete."

artifacts:
  files:
    - ../app.zip