version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install Poetry (correct path)
      - pip install --no-index --find-links=./packages ./packages/poetry-2.1.3-py3-none-any.whl

      # Configure Poetry
      - poetry config virtualenvs.create false
      - export PIP_NO_INDEX=1
      - export PIP_FIND_LINKS=./packages
      - yum install -y postgresql-devel
      - poetry install --without dev --no-interaction --no-ansi


  pre_build:
    commands:
      - poetry run python manage.py migrate --noinput
      - poetry run python manage.py collectstatic --noinput

  build:
    commands:
      - zip -r app.zip . -x "*.git*" "media/*" "*.pyc" "*__pycache__*" "packages/*"

  post_build:
    commands:
      - echo "Build completed."