version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.0
    commands:
      - pip install --upgrade pip
      # Install pipx (best way to manage Poetry)
      - python -m pip install --user pipx
      - python -m pipx ensurepath
      - pipx install poetry==1.7.1  # Explicit version
      - poetry --version  # Verify installation
      - poetry install --no-interaction --no-ansi

  pre_build:
    commands:
      - poetry run python manage.py migrate --noinput
      - poetry run python manage.py collectstatic --noinput

  build:
    commands:
      - zip -r ../app.zip . -x "*.git*" "media/*" "media-/*" "*.pyc" "*__pycache__*"

  post_build:
    commands:
      - echo "Build and packaging complete."

artifacts:
  files:
    - ../app.zip