version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - |
        pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="/root/.local/bin:$PATH"
        source ~/.bashrc  # Optional: Ensures env is refreshed if needed
        poetry config virtualenvs.create false  # Optional: Use system env
        poetry install --no-interaction --no-ansi

  pre_build:
    commands:
      - |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run python manage.py migrate --noinput
        poetry run python manage.py collectstatic --noinput

  build:
    commands:
      - zip -r ../app.zip . -x "*.git*" "media/*" "media-/*" "*.pyc" "*__pycache__*"

  post_build:
    commands:
      - echo "Build and packaging complete."

artifacts:
  files:
    - ../app.zip
