# Generated by Django 5.2.1 on 2025-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Time")),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Participants"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="activities/", verbose_name="Image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Organization Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "street",
                    models.CharField(max_length=200, verbose_name="Street Address"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Website URL")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "youtube",
                    models.URLField(blank=True, verbose_name="YouTube Channel"),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook Page")),
                (
                    "instagram",
                    models.URLField(blank=True, verbose_name="Instagram Profile"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="organization/", verbose_name="Logo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organization",
            },
        ),
    ]
