# Generated by Django 5.2.1 on 2025-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="future_event",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a future event.",
                verbose_name="Future Event",
            ),
        ),
    ]
