# Generated by Django 5.2.1 on 2025-07-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_activity_future_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="is_active",
        ),
    ]
