# Generated by Django 5.2.1 on 2025-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_activity_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="activities/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
    ]
