# Generated by Django 5.2.1 on 2025-08-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_activity_image_activityimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
