# Generated by Django 5.2.1 on 2025-06-17 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the Photo model.

    Creates the Photo table with the following fields:
    - id: Primary key, auto-incrementing.
    - title: CharField, max length 200, stores the photo title.
    - image: ImageField, stores the image file under core/images/ directory.
    - description: Optional text field for additional photo details.
    - uploaded_at: DateTimeField, records the upload timestamp with default as current time.

    The model is ordered by uploaded_at in descending order.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title or name of the photo", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="The actual image file. Will be stored in core/images/ directory",
                        upload_to="core/images/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or additional information about the photo",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of when the photo was uploaded",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
