# Generated by Django 5.2.1 on 2025-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="url_path",
            field=models.CharField(
                blank=True, help_text="The URL path to access the image", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                help_text="The actual image file. Will be stored in core/static/core/images/ directory",
                upload_to="core/images/",
            ),
        ),
    ]
