# Generated by Django 5.2.1 on 2025-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add the 'url_path' field to the Photo model
    and update the 'image' field's upload path and help text.

    - Adds 'url_path' CharField to store the URL path for accessing images.
    - Alters 'image' ImageField to change the upload directory to 'core/images/'
      and update the help text accordingly.
    """

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="url_path",
            field=models.CharField(
                blank=True, help_text="The URL path to access the image", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                help_text="The actual image file. Will be stored in core/static/core/images/ directory",
                upload_to="core/images/",
            ),
        ),
    ]
