# Generated by Django 5.2.1 on 2025-06-15 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to create the AdminReply and Message models.

    - AdminReply: Stores admin responses with fields for answer ID, subject, message, and creation timestamp.
    - Message: Stores user messages with fields for name, email, subject, message content, read status, and creation timestamp.

    Both models include verbose names (in Swedish) and ordering by creation date descending.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_id", models.IntegerField()),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Admin Svar",
                "verbose_name_plural": "Admin Svar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Meddelande",
                "verbose_name_plural": "Meddelanden",
                "ordering": ["-created_at"],
            },
        ),
    ]
