# Generated by Django 5.2.1 on 2025-06-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_replied",
        ),
    ]
