# Generated by Django 5.2.1 on 2025-06-13 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_remove_message_is_replied"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_id", models.IntegerField()),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Admin Svar",
                "verbose_name_plural": "Admin Svar",
                "ordering": ["-created_at"],
            },
        ),
    ]
